services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BACKEND: "http://localhost:8000"
    depends_on:
      - backend-mock
    ports:
      - 80:80

  backend-mock:
    build:
      context: .
      dockerfile: Dockerfile-back
    ports:
     - 8000:8000
