FROM node:22-alpine

WORKDIR /app

COPY /testing/generate-fake-notes.mjs /app/
COPY /testing/package.json /app

RUN mkdir -p testing && npm i && npm run generate

CMD [ "npm", "run", "backend"]

EXPOSE 8000